insert into stock (id, company, symbol, sector, price) values (1, 'Model N, Inc.', 'MODN', 'Technology', '706.11');
insert into stock (id, company, symbol, sector, price) values (2, 'Alexandria Real Estate Equities, Inc.', 'ARE', 'Consumer Services', '624.60');
insert into stock (id, company, symbol, sector, price) values (3, 'Advent Claymore Convertible Securities and Income Fund', 'AVK', 'n/a', '1535.16');
insert into stock (id, company, symbol, sector, price) values (4, 'Pacific Drilling S.A.', 'PACD', 'Energy', '733.48');
insert into stock (id, company, symbol, sector, price) values (5, 'Align Technology, Inc.', 'ALGN', 'Health Care', '1222.02');
insert into stock (id, company, symbol, sector, price) values (6, 'Gogo Inc.', 'GOGO', 'Consumer Services', '306.60');
insert into stock (id, company, symbol, sector, price) values (7, 'Royal Bank Of Canada', 'RY^S', 'n/a', '1969.91');
insert into stock (id, company, symbol, sector, price) values (8, 'Alliance Holdings GP, L.P.', 'AHGP', 'Energy', '782.87');
insert into stock (id, company, symbol, sector, price) values (9, 'Bank of Hawaii Corporation', 'BOH', 'Finance', '353.32');
insert into stock (id, company, symbol, sector, price) values (10, 'Brookfield Real Assets Income Fund Inc.', 'RA', 'n/a', '1557.15');
insert into stock (id, company, symbol, sector, price) values (11, 'United Community Financial Corp.', 'UCFC', 'Finance', '1794.65');
insert into stock (id, company, symbol, sector, price) values (12, 'Galmed Pharmaceuticals Ltd.', 'GLMD', 'Health Care', '1116.99');
insert into stock (id, company, symbol, sector, price) values (13, 'Farmers Capital Bank Corporation', 'FFKT', 'Finance', '1372.36');
insert into stock (id, company, symbol, sector, price) values (14, 'SkyWest, Inc.', 'SKYW', 'Transportation', '1402.34');
insert into stock (id, company, symbol, sector, price) values (15, 'TravelCenters of America LLC', 'TANNZ', 'Consumer Durables', '768.85');
insert into stock (id, company, symbol, sector, price) values (16, 'Anthem, Inc.', 'ANTM', 'Health Care', '647.77');
insert into stock (id, company, symbol, sector, price) values (17, 'Calamos Global Dynamic Income Fund', 'CHW', 'n/a', '870.59');
insert into stock (id, company, symbol, sector, price) values (18, 'Hess Midstream Partners LP', 'HESM', 'Energy', '1316.72');
insert into stock (id, company, symbol, sector, price) values (19, 'Third Point Reinsurance Ltd.', 'TPRE', 'Finance', '363.54');
insert into stock (id, company, symbol, sector, price) values (20, 'Nuveen Build America Bond Fund', 'NBB', 'n/a', '769.47');
insert into stock (id, company, symbol, sector, price) values (21, 'Hunter Maritime Acquisition Corp.', 'HUNTU', 'Transportation', '1497.37');
insert into stock (id, company, symbol, sector, price) values (22, 'Vornado Realty Trust', 'VNO^G', 'n/a', '1720.19');
insert into stock (id, company, symbol, sector, price) values (23, 'Sonus Networks, Inc.', 'SONS', 'Technology', '1809.50');
insert into stock (id, company, symbol, sector, price) values (24, 'Reading International Inc', 'RDIB', 'Consumer Services', '101.25');
insert into stock (id, company, symbol, sector, price) values (25, 'Community Bank System, Inc.', 'CBU', 'Finance', '1145.04');
insert into stock (id, company, symbol, sector, price) values (26, 'HomeTrust Bancshares, Inc.', 'HTBI', 'Finance', '435.12');
insert into stock (id, company, symbol, sector, price) values (27, 'Chesapeake Energy Corporation', 'CHK^D', 'n/a', '1220.62');
insert into stock (id, company, symbol, sector, price) values (28, 'Janus Henderson Group plc', 'JHG', 'Finance', '1281.01');
insert into stock (id, company, symbol, sector, price) values (29, 'Mitsubishi UFJ Financial Group Inc', 'MTU', 'Finance', '220.03');
insert into stock (id, company, symbol, sector, price) values (30, 'Methanex Corporation', 'MEOH', 'Basic Industries', '820.12');
insert into stock (id, company, symbol, sector, price) values (31, 'First Data Corporation', 'FDC', 'Miscellaneous', '1295.51');
insert into stock (id, company, symbol, sector, price) values (32, 'Teekay Tankers Ltd.', 'TNK', 'Consumer Services', '1619.83');
insert into stock (id, company, symbol, sector, price) values (33, 'UFP Technologies, Inc.', 'UFPT', 'Capital Goods', '1350.21');
insert into stock (id, company, symbol, sector, price) values (34, 'Infinity Property and Casualty Corporation', 'IPCC', 'Finance', '148.05');
insert into stock (id, company, symbol, sector, price) values (35, 'Omega Flex, Inc.', 'OFLX', 'Capital Goods', '257.38');
insert into stock (id, company, symbol, sector, price) values (36, 'Motif Bio plc', 'MTFBW', 'Health Care', '530.09');
insert into stock (id, company, symbol, sector, price) values (37, 'Comerica Incorporated', 'CMA', 'Finance', '205.35');
insert into stock (id, company, symbol, sector, price) values (38, 'Old Dominion Freight Line, Inc.', 'ODFL', 'Transportation', '193.60');
insert into stock (id, company, symbol, sector, price) values (39, 'Capitala Finance Corp.', 'CPTAG', 'n/a', '1634.02');
insert into stock (id, company, symbol, sector, price) values (40, 'Encore Wire Corporation', 'WIRE', 'Capital Goods', '780.15');
insert into stock (id, company, symbol, sector, price) values (41, 'Paycom Software, Inc.', 'PAYC', 'Technology', '679.41');
insert into stock (id, company, symbol, sector, price) values (42, 'Lazard Global Total Return and Income Fund', 'LGI', 'n/a', '1653.32');
insert into stock (id, company, symbol, sector, price) values (43, 'Vince Holding Corp.', 'VNCE', 'Consumer Services', '1115.68');
insert into stock (id, company, symbol, sector, price) values (44, 'First Merchants Corporation', 'FRME', 'Finance', '1734.59');
insert into stock (id, company, symbol, sector, price) values (45, 'Navigant Consulting, Inc.', 'NCI', 'Consumer Services', '887.45');
insert into stock (id, company, symbol, sector, price) values (46, 'Kimball Electronics, Inc.', 'KE', 'Technology', '363.42');
insert into stock (id, company, symbol, sector, price) values (47, 'DTE Energy Company', 'DTE', 'Public Utilities', '801.83');
insert into stock (id, company, symbol, sector, price) values (48, 'AmTrust Financial Services, Inc.', 'AFSI^A', 'n/a', '654.05');
insert into stock (id, company, symbol, sector, price) values (49, 'XBiotech Inc.', 'XBIT', 'Health Care', '861.70');
insert into stock (id, company, symbol, sector, price) values (50, 'Intec Pharma Ltd.', 'NTEC', 'Health Care', '683.62');
insert into stock (id, company, symbol, sector, price) values (51, 'Petroquest Energy Inc', 'PQ', 'Energy', '829.72');
insert into stock (id, company, symbol, sector, price) values (52, 'Sasol Ltd.', 'SSL', 'Energy', '636.87');
insert into stock (id, company, symbol, sector, price) values (53, 'KeyCorp', 'KEY^I', 'n/a', '1626.41');
insert into stock (id, company, symbol, sector, price) values (54, 'East West Bancorp, Inc.', 'EWBC', 'Finance', '91.71');
insert into stock (id, company, symbol, sector, price) values (55, 'Donegal Group, Inc.', 'DGICB', 'Finance', '1422.52');
insert into stock (id, company, symbol, sector, price) values (56, 'iPath US Treasury 10-year Bull ETN', 'DTYL', 'Finance', '1892.64');
insert into stock (id, company, symbol, sector, price) values (57, 'FNB Bancorp', 'FNBG', 'Finance', '1448.95');
insert into stock (id, company, symbol, sector, price) values (58, 'Old Second Bancorp, Inc.', 'OSBC', 'Finance', '1187.63');
insert into stock (id, company, symbol, sector, price) values (59, 'Mid-America Apartment Communities, Inc.', 'MAA^I', 'n/a', '1455.46');
insert into stock (id, company, symbol, sector, price) values (60, 'Dominion Energy, Inc.', 'DCUD', 'Public Utilities', '1238.18');
insert into stock (id, company, symbol, sector, price) values (61, 'Vident International Equity Fund', 'VIDI', 'n/a', '1739.04');
insert into stock (id, company, symbol, sector, price) values (62, 'Green Plains, Inc.', 'GPRE', 'Basic Industries', '453.34');
insert into stock (id, company, symbol, sector, price) values (63, 'Essendant Inc.', 'ESND', 'Consumer Services', '1958.20');
insert into stock (id, company, symbol, sector, price) values (64, 'Jensyn Acquistion Corp.', 'JSYNR', 'Finance', '994.39');
insert into stock (id, company, symbol, sector, price) values (65, 'Southern California Edison Company', 'SCE^G', 'n/a', '988.35');
insert into stock (id, company, symbol, sector, price) values (66, 'Intersections, Inc.', 'INTX', 'Technology', '864.98');
insert into stock (id, company, symbol, sector, price) values (67, 'Evertec, Inc.', 'EVTC', 'Technology', '1149.94');
insert into stock (id, company, symbol, sector, price) values (68, 'ManpowerGroup', 'MAN', 'Technology', '213.47');
insert into stock (id, company, symbol, sector, price) values (69, 'Validus Holdings, Ltd.', 'VR^A', 'n/a', '1738.95');
insert into stock (id, company, symbol, sector, price) values (70, 'Global X Health & Wellness Thematic ETF', 'BFIT', 'n/a', '1894.19');
insert into stock (id, company, symbol, sector, price) values (71, 'Calamos Global Dynamic Income Fund', 'CHW', 'n/a', '535.12');
insert into stock (id, company, symbol, sector, price) values (72, 'Vertex Pharmaceuticals Incorporated', 'VRTX', 'Health Care', '534.41');
insert into stock (id, company, symbol, sector, price) values (73, 'Ellington Residential Mortgage REIT', 'EARN', 'Consumer Services', '380.25');
insert into stock (id, company, symbol, sector, price) values (74, 'Wintrust Financial Corporation', 'WTFCW', 'Finance', '1267.93');
insert into stock (id, company, symbol, sector, price) values (75, 'TC PipeLines, LP', 'TCP', 'Public Utilities', '769.65');
insert into stock (id, company, symbol, sector, price) values (76, 'Kinsale Capital Group, Inc.', 'KNSL', 'Finance', '1067.87');
insert into stock (id, company, symbol, sector, price) values (77, 'Sysco Corporation', 'SYY', 'Consumer Non-Durables', '1818.93');
insert into stock (id, company, symbol, sector, price) values (78, 'Blackrock Muni Intermediate Duration Fund Inc', 'MUI', 'n/a', '530.71');
insert into stock (id, company, symbol, sector, price) values (79, 'Encore Wire Corporation', 'WIRE', 'Capital Goods', '1220.70');
insert into stock (id, company, symbol, sector, price) values (80, 'WAVE Life Sciences Ltd.', 'WVE', 'Health Care', '605.16');
insert into stock (id, company, symbol, sector, price) values (81, 'Polar Power, Inc.', 'POLA', 'n/a', '334.15');
insert into stock (id, company, symbol, sector, price) values (82, 'Neonode Inc.', 'NEON', 'Capital Goods', '1333.44');
insert into stock (id, company, symbol, sector, price) values (83, 'The Trade Desk, Inc.', 'TTD', 'Technology', '724.78');
insert into stock (id, company, symbol, sector, price) values (84, 'Pioneer Natural Resources Company', 'PXD', 'Energy', '1946.28');
insert into stock (id, company, symbol, sector, price) values (85, 'Vonage Holdings Corp.', 'VG', 'Public Utilities', '1624.99');
insert into stock (id, company, symbol, sector, price) values (86, 'Avista Healthcare Public Acquisition Corp.', 'AHPAU', 'Finance', '108.35');
insert into stock (id, company, symbol, sector, price) values (87, 'Eaton Vance Municipal Income Trust', 'EVN', 'n/a', '1644.52');
insert into stock (id, company, symbol, sector, price) values (88, 'Vanguard International Dividend Appreciation ETF', 'VIGI', 'n/a', '1099.49');
insert into stock (id, company, symbol, sector, price) values (89, 'Envestnet, Inc', 'ENV', 'Miscellaneous', '893.45');
insert into stock (id, company, symbol, sector, price) values (90, 'Acadia Realty Trust', 'AKR', 'Consumer Services', '276.17');
insert into stock (id, company, symbol, sector, price) values (91, 'Pieris Pharmaceuticals, Inc.', 'PIRS', 'Health Care', '511.69');
insert into stock (id, company, symbol, sector, price) values (92, 'China Rapid Finance Limited', 'XRF', 'Finance', '629.45');
insert into stock (id, company, symbol, sector, price) values (93, 'AmTrust Financial Services, Inc.', 'AFSS', 'Finance', '935.13');
insert into stock (id, company, symbol, sector, price) values (94, 'Forum Merger Corporation', 'FMCIU', 'Finance', '772.64');
insert into stock (id, company, symbol, sector, price) values (95, 'First Trust Multi Cap Growth AlphaDEX Fund', 'FAD', 'n/a', '1476.44');
insert into stock (id, company, symbol, sector, price) values (96, 'Tuniu Corporation', 'TOUR', 'Consumer Services', '1077.28');
insert into stock (id, company, symbol, sector, price) values (97, 'Bank of America Corporation', 'BML^G', 'n/a', '1936.00');
insert into stock (id, company, symbol, sector, price) values (98, 'Flowserve Corporation', 'FLS', 'Capital Goods', '1023.14');
insert into stock (id, company, symbol, sector, price) values (99, 'Bank of America Corporation', 'BAC^D', 'n/a', '1889.89');
insert into stock (id, company, symbol, sector, price) values (100, 'Oxford Industries, Inc.', 'OXM', 'Consumer Non-Durables', '580.28');
